name: Ejecutar Quarto y enviar email

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base r-base-dev curl pandoc texlive-xetex
          sudo apt-get install -y r-cran-rmarkdown r-cran-knitr r-cran-readxl r-cran-dplyr r-cran-ggplot2 r-cran-forecast r-cran-factoextra r-cran-corrplot r-cran-lubridate
      
      - name: Instalar Quarto
        run: |
          curl -LO https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.450/quarto-1.3.450-linux-amd64.deb
          sudo dpkg -i quarto-1.3.450-linux-amd64.deb
      
      - name: Renderizar Quarto
        run: quarto render ACT_3_G002.qmd --to html
      
      - name: Enviar email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "📊 Informe Adventure Works - Semanal"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USER }}
          body: |
            Hola,
            
            Se adjunta el informe automatizado de Adventure Works.
            
            Generado automáticamente cada lunes.
            
            Saludos,
            Sistema de automatización
          attachments: ACT_3_G002.html
